/*
 * Click nbfs://nbhost            @Override
            public void paintIcon(Component c, Graphics g, int x, int y) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public int getIconWidth() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public int getIconHeight() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        }SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Iniciador;

import com.Recursos.Modifiers.RoundBorder;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 * @author exosh
 */
public class LogIn extends javax.swing.JFrame {

    private static final String DB_URL = "jdbc:mysql://localhost:3306/Javamon";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "root";

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setofGUI();
        addKeyListeners();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel = setBackgroundImage("fondo1");
        title = setBackgroundImage("javamonTitle");
        logContainer = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passwd = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        passwdField = new javax.swing.JPasswordField();
        settings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame"); // NOI18N

        panel.setBackground(new java.awt.Color(0, 0, 255));
        panel.setName(""); // NOI18N

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
                titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 389, Short.MAX_VALUE)
        );
        titleLayout.setVerticalGroup(
                titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 178, Short.MAX_VALUE)
        );

        logContainer.setBackground(new java.awt.Color(255, 255, 255));

        user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user.setText("Usuario:");

        userField.setText("Usuario");

        passwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwd.setText("Contraseña:");

        iniciarSesion.setText("Iniciar Sesion");
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    iniciarSesionActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        registrar.setText("Registrarse");
        registrar.setToolTipText("");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        passwdField.setText("Contraseña");

        javax.swing.GroupLayout logContainerLayout = new javax.swing.GroupLayout(logContainer);
        logContainer.setLayout(logContainerLayout);
        logContainerLayout.setHorizontalGroup(
                logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(logContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(logContainerLayout.createSequentialGroup()
                                                .addGroup(logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(passwd)
                                                        .addComponent(user))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(userField)
                                                        .addComponent(passwdField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                        .addGroup(logContainerLayout.createSequentialGroup()
                                                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(iniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        logContainerLayout.setVerticalGroup(
                logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(logContainerLayout.createSequentialGroup()
                                .addContainerGap(52, Short.MAX_VALUE)
                                .addGroup(logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(user)
                                        .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwd)
                                        .addComponent(passwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(logContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(iniciarSesion)
                                        .addComponent(registrar))
                                .addContainerGap(52, Short.MAX_VALUE))
        );

        settings.setBackground(panel.getBackground());
        settings.setBorder(null);
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap(209, Short.MAX_VALUE)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                                .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
        );
        panelLayout.setVerticalGroup(
                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(logContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Cambiamos PREFERRED_SIZE por DEFAULT_SIZE y agregamos Short.MAX_VALUE
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Igual que arriba
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JPanel setBackgroundImage(String archiveName) {
        JPanel panel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                // Cargar la imagen
                ImageIcon backgroundIcon = new ImageIcon("src/main/java/com/Recursos/" + archiveName + ".png"); // Cambia la ruta según tu imagen
                Image backgroundImage = backgroundIcon.getImage();
                // Dibujar la imagen como fondo
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            }
        };
        return panel;
    }

    private void setofGUI() {
        title.setOpaque(false);
        //Settea el Boton de Settings
        ImageIcon icon = new ImageIcon("src/main/java/com/Recursos/utils/engranaje.png");
        Icon image = new ImageIcon(icon.getImage());
        settings.setContentAreaFilled(false);
        settings.setBorderPainted(false);
        settings.setFocusPainted(false);
        settings.setOpaque(false);
        settings.setIcon(image);
        settings.setBorder(new EmptyBorder(0, 0, 0, 0));
        //Setteo del boton de inicio de sesion
        iniciarSesion.setBorder(new RoundBorder(10));
        iniciarSesion.setFocusPainted(false);
        iniciarSesion.setOpaque(false);
        iniciarSesion.setBackground(new Color(0, 0, 0, 255));
        iniciarSesion.setContentAreaFilled(false);
        //Setteo del boton de registro
        registrar.setBorder(new RoundBorder(10));
        registrar.setFocusPainted(false);
        registrar.setOpaque(false);
        registrar.setBackground(new Color(0, 0, 0, 255));
        registrar.setContentAreaFilled(false);
        //Settea la transparencia del panel de inicio de Sesion
        logContainer.setBackground(new Color(255, 255, 255, 180));
    }
    public void addKeyListeners() {
        KeyListener enterKeyListener = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                // No utilizado
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    try {
                        iniciarSesionActionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "EnterKeyPressed"));
                    } catch (SQLException | ClassNotFoundException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(panel, "Ocurrió un error al iniciar sesión.");
                    }
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                // No utilizado
            }
        };

        // Agregar el KeyListener a los campos de texto
        userField.addKeyListener(enterKeyListener);
        passwdField.addKeyListener(enterKeyListener);
    }
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Registro");
        JLabel userLabel = new JLabel("Usuario:");
        JTextField userField = new JTextField();
        JLabel passLabel = new JLabel("Contraseña");
        JPasswordField passField = new JPasswordField();
        JButton registerButton = new JButton("Registrar");
        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (registerUser(userField.getText(), passField.getText())) {
                    JOptionPane.showMessageDialog(panel, "Registro exitoso!");
                } else {
                    JOptionPane.showMessageDialog(panel, "El usuario ya existe.");
                }
            }
        });
        frame.add(userLabel);
        frame.add(userField);
        frame.add(passLabel);
        frame.add(passField);
        frame.add(registerButton);
        frame.setSize(300, 200);
        frame.setLayout(new GridLayout(3, 2));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_registrarActionPerformed

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_iniciarSesionActionPerformed
        // TODO add your handling code here:
        String username = userField.getText();
        String password = new String(passwdField.getPassword());

        if (authenticateUser(username, password)) {
            JOptionPane.showMessageDialog(panel, "Login exitoso!");
            new initialMenu(username, password).setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(panel, "Usuario o contraseña incorrectos.");
        }
    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsActionPerformed

    private static boolean authenticateUser(String username, String password) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String query = "SELECT * FROM users WHERE name = ? AND passwd = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, username);
            stmt.setString(2, password);

            ResultSet rs = stmt.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    private static boolean registerUser(String username, String password) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String checkQuery = "SELECT * FROM users WHERE name = ?";
            PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
            checkStmt.setString(1, username);

            ResultSet rs = checkStmt.executeQuery();
            if (rs.next()) {
                return false;
            }

            String insertQuery = "INSERT INTO users (name, passwd) VALUES (?, ?)";
            PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
            insertStmt.setString(1, username);
            insertStmt.setString(2, password);
            insertStmt.executeUpdate();

            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new LogIn().setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JPanel logContainer;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel passwd;
    private javax.swing.JPasswordField passwdField;
    private javax.swing.JButton registrar;
    private javax.swing.JButton settings;
    private javax.swing.JPanel title;
    private javax.swing.JLabel user;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
