/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Tienda;

import com.BattleCPU.resources.MoneyManager;
import com.BattleCPU.resources.Pokemon;
import com.PokemonContainer.PCLoader;
import com.PokemonContainer.PokemonContainerGUI;
import com.mysql.cj.xdevapi.UpdateStatement;

import javax.sound.sampled.LineUnavailableException;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author exosh
 */
public class ManagerPokemons extends javax.swing.JFrame {
    int precio;
    private static String url;
    private static String user;
    private static String psswd;
    private static java.sql.Connection con;
    String uuid;
    ArrayList<Pokemon> pokemons;
    String name;
    Pokemon p;
    /**
     * Creates new form ManagerPokemons
     */
    public ManagerPokemons(ArrayList<Pokemon> equipo, String name, Pokemon pComprar, String uuid) throws SQLException, ClassNotFoundException {
        this.p = pComprar;
        this.pokemons = equipo;
        this.name = name;
        this.uuid = uuid;
        initComponents();
        jLabel1.setText(pComprar.getNombre());

        ImageIcon icon = new ImageIcon("src/main/java/com/Recursos/pokemonImages/" + pComprar.getEspecie().toLowerCase() + ".png");
        Icon image = new ImageIcon(icon.getImage().getScaledInstance(250, 250, Image.SCALE_DEFAULT));
        jLabel2.setIcon(image);

        precio = pComprar.getHp() + pComprar.getAtq() + pComprar.getDef() + pComprar.getVel() + pComprar.getEdf() + pComprar.getEat() * 10;
        jLabel3.setText("Precio: " + precio);
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    new PokemonShop(pokemons, name, uuid).setVisible(true);
                } catch (LineUnavailableException ex) {
                    throw new RuntimeException(ex);
                } catch (SQLException ex) {
                    throw new RuntimeException(ex);
                } catch (ClassNotFoundException ex) {
                    throw new RuntimeException(ex);
                }
            }
        });

        jLabel5.setText(String.valueOf(getDinero()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nombre");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Precio");

        jButton1.setText("Comprar");
        jButton1.setActionCommand("button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (LineUnavailableException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel4.setText("Dinero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException, LineUnavailableException {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int dinero = getDinero();
        if(precio > dinero){
            JOptionPane.showMessageDialog(this, "No tienes suficiente dinero");
        }else{
            String aux;
            if(p.getTipo2().equals("")) {
                aux = "null";
            } else{
                aux = p.getTipo2();
            }
            System.out.println(p.getNombre());
            String insertQuery = "INSERT INTO pokemon (idTrainer,trainerName,`name`, specie,type1,type2,hp,atk,def,eAtk,eDef,spd,team,move1,move2,move3,move4)" +
                    " VALUES "+"("+uuid + ",'"+ name + "','"+ p.getNombre() + "','"+ p.getEspecie()+"','"+p.getTipo1()+"','"+aux+"',"+
                    p.getHp()+","+p.getAtq()+","+p.getDef()+","+p.getEat()+","+p.getEdf()+","+p.getVel()+ "," + "false"+","+
                    p.getM1()+","+p.getM2()+","+p.getM3()+","+p.getM4()+")";
            PreparedStatement insertStmt = con.prepareStatement(insertQuery);
            insertStmt.executeUpdate();
            MoneyManager m = new MoneyManager(precio * -1,uuid);
            m.updateMoney();
            new PokemonShop(pokemons, name, uuid).setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public int getDinero() throws ClassNotFoundException, SQLException {
        Class.forName("com.mysql.cj.jdbc.Driver");
        url = "jdbc:mysql://localhost:3306/Javamon";
        user = "root";
        psswd = "root";
        con = DriverManager.getConnection(url, user, psswd);
        String query = "SELECT * FROM users WHERE idUsuario like " + "'" + uuid + "'";
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        System.out.println("Recibiendo Dinero...");
        int dinero = 0;
        while (rs.next()) {
            dinero = rs.getInt("money");
        }
        return dinero;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
