/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Recursos.reusableCode;

import com.BattleCPU.resources.*;
import com.Recursos.Modifiers.RoundBorder;

import javax.sound.sampled.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 * @author exosh
 */
public class pokemonInterface extends JFrame {
    ArrayList<Pokemon> listPokemon;
    Clip musica;

    public pokemonInterface(ArrayList<Pokemon> listPokemon, Pokemon pokemonSelected, Clip clip) throws SQLException, ClassNotFoundException {
        this.listPokemon = listPokemon;
        this.musica = clip;
        initComponents(pokemonSelected);
        add(loadTeam(listPokemon), BorderLayout.EAST);
        paint(pokemonSelected);
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Pokemon pokemonSelected) {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setBackground(new java.awt.Color(153, 153, 153));

        nickname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setText("Lv.");

        level.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout lvPanelLayout = new javax.swing.GroupLayout(lvPanel);
        lvPanel.setLayout(lvPanelLayout);
        lvPanelLayout.setHorizontalGroup(
            lvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lvPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lvPanelLayout.setVerticalGroup(
            lvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lvPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(lvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(level))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(nickname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1144, Short.MAX_VALUE)
                .addComponent(lvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(titulo, java.awt.BorderLayout.NORTH);

        main.setBackground(new java.awt.Color(211, 251, 255));

        type1.setBackground(new java.awt.Color(102, 102, 102));
        type1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        type1.setText("Tipo1");

        name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        type2.setBackground(new java.awt.Color(102, 102, 102));
        type2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        type2.setText("Type2");

        trainerID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Ataque");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Defensa");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Ataque Especial");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Defensa Especial");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Velocidad");

        atq.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        def.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        eat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        edf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        vel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout statsLayout = new javax.swing.GroupLayout(stats);
        stats.setLayout(statsLayout);
        statsLayout.setHorizontalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statsLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edf))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsLayout.createSequentialGroup()
                        .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atq, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(statsLayout.createSequentialGroup()
                        .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(def, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(21, 21, 21))
        );
        statsLayout.setVerticalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(atq))
                .addGap(18, 18, 18)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(def))
                .addGap(18, 18, 18)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(eat))
                .addGap(18, 18, 18)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(edf))
                .addGap(18, 18, 18)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(vel))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout movesLayout = new javax.swing.GroupLayout(moves);
        moves.setLayout(movesLayout);
        movesLayout.setHorizontalGroup(
            movesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        movesLayout.setVerticalGroup(
            movesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        btnObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjetoActionPerformed(evt);
            }
        });

        habilidad.setText("HABILIDAD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hEfect, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(habilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hEfect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trainerID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(moves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(type1)
                        .addGap(20, 20, 20)
                        .addComponent(type2)))
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(157, 157, 157))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(trainerID)))
                .addGap(18, 18, 18)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainLayout.createSequentialGroup()
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(type2)
                                        .addComponent(type1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(0, 92, Short.MAX_VALUE)
                                .addComponent(moves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))))
        );

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObjetoActionPerformed
    public JPanel loadTeam(ArrayList<Pokemon> equipoPokemon) {
        JPanel team = new JPanel(new GridBagLayout());
        team.setBorder(new EmptyBorder(0,10,0,10));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(0, 10, 5, 5); // 5px de padding en todos los lados

        for (int i = 0; i < equipoPokemon.size(); i++) {
            gbc.gridx = 0; // Mantenemos la columna en 0
            gbc.gridy = i; // Incrementamos la fila para cada Pokémon
            int indice = i;
            JButton bttn = new JButton();
            bttn.setPreferredSize(new Dimension(100, getHeight() / equipoPokemon.size() - 10));
            ImageIcon icon = new ImageIcon("src/main/java/com/Recursos/pokemonImages/" + equipoPokemon.get(i).getEspecie().toLowerCase() + ".png");
            Icon image = new ImageIcon(icon.getImage().getScaledInstance(90, 90, Image.SCALE_DEFAULT));
            bttn.setIcon(image);
            bttn.setBorder(new RoundBorder(9));
            bttn.setBorder(BorderFactory.createCompoundBorder(new RoundBorder(9), BorderFactory.createEmptyBorder(5, 10, 5, 10)));
            bttn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    paint(listPokemon.get(indice));
                }
            });
            team.add(bttn, gbc);
        }
        return team;
    }
    public void paint(Pokemon p){
        ImageIcon pokemon = new ImageIcon("src/main/java/com/Recursos/pokemonImages/" + p.getEspecie().toLowerCase() + ".png");
        Icon imagePokemon = new ImageIcon(pokemon.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_SMOOTH));
        jLabel2.setIcon(imagePokemon);
        type1.setText(p.getTipo1());
        type2.setText(p.getTipo2() == null ? "" : p.getTipo2());
        level.setText(p.getNivel() + "");
        lvPanel.setBackground(new Color(255,255,255,180));
        name.setText(p.getEspecie());

        nickname.setText(p.getNombre());
        nickname.setBackground(new Color(255,255,255,180));
        nickname.setBorder(BorderFactory.createCompoundBorder(new RoundBorder(9,colorContrario(p.getColorType()), 3), new EmptyBorder(5,10,5,10)));
        nickname.setOpaque(true);

        titulo.setBackground(p.getColorType());
        trainerID.setText(p.getIdTrainer());
        atq.setText(String.valueOf(p.getAtq()));
        def.setText(String.valueOf(p.getDef()));
        eat.setText(String.valueOf(p.getEat()));
        edf.setText(String.valueOf(p.getEdf()));
        vel.setText(String.valueOf(p.getVel()));
        if (p.getObjeto() != null) {
            ImageIcon icon = new ImageIcon("src/main/java/com/Recursos/objetos/" + p.getObjeto().toLowerCase() + ".png");
            Icon image = new ImageIcon(icon.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
            btnObjeto.setIcon(image);
        }
        actualizarPanelMoves(p);
        crie(p);
    }
    public void crie(Pokemon p){
        try {
            File archivoSonido = new File("src/main/java/com/Recursos/Cries/" + p.getEspecie().toLowerCase() + ".wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(archivoSonido);

            Clip clip = AudioSystem.getClip();

            clip.open(audioStream);
            clip.start();

        } catch (UnsupportedAudioFileException e) {
            System.out.println("El archivo de audio no es compatible.");
            e.printStackTrace();
        } catch (IOException e) {
            System.out.println("Hubo un problema al leer el archivo de audio.");
            e.printStackTrace();
        } catch (LineUnavailableException e) {
            System.out.println("El sistema no puede reproducir el sonido.");
            e.printStackTrace();
        }
    }
    public Color colorContrario (Color cambiar){
        Color aCambiar = cambiar;
        aCambiar = new Color(255-aCambiar.getRed(),255 - aCambiar.getGreen(), 255 - aCambiar.getBlue());
        return aCambiar;
    }
    public JPanel movimientos(Pokemon p) {
        JPanel movs = new JPanel(new GridLayout(p.getMovimientos().length, 1)); // Layout adaptable
        for (int i = 0; i < p.getMovimientos().length; i++) {
            JButton mov = new JButton(p.getMovimientos()[i].getNombre());
            movs.add(mov);
        }
        return movs;
    }
    public GroupLayout layoutMoves() {
        GroupLayout gp = new javax.swing.GroupLayout(moves);
        moves.setLayout(gp);
        gp.setHorizontalGroup(
                gp.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 287, Short.MAX_VALUE)
        );
        gp.setVerticalGroup(
                gp.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 409, Short.MAX_VALUE)
        );
        return gp;
    }
    public void actualizarPanelMoves(Pokemon p) {
        moves.removeAll();
        JPanel nuevoContenido = movimientos(p);
        GroupLayout gp = layoutMoves();
        gp.setHorizontalGroup(
                gp.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nuevoContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );
        gp.setVerticalGroup(
                gp.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nuevoContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        moves.revalidate();
        moves.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atq = new javax.swing.JLabel();
    private javax.swing.JButton btnObjeto = new javax.swing.JButton();
    private javax.swing.JLabel def= new javax.swing.JLabel();
    private javax.swing.JLabel eat= new javax.swing.JLabel();
    private javax.swing.JLabel edf= new javax.swing.JLabel();
    private javax.swing.JLabel hEfect= new javax.swing.JLabel();
    private javax.swing.JLabel habilidad= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel10= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel11= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel12= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel13= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel2= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel5= new javax.swing.JLabel();
    private javax.swing.JLabel jLabel9= new javax.swing.JLabel();
    private javax.swing.JPanel jPanel1= new javax.swing.JPanel();
    private javax.swing.JLabel level= new javax.swing.JLabel();
    private javax.swing.JPanel lvPanel= new javax.swing.JPanel();
    private javax.swing.JPanel main= new javax.swing.JPanel();
    private javax.swing.JPanel moves= new javax.swing.JPanel();
    private javax.swing.JLabel name= new javax.swing.JLabel();
    private javax.swing.JLabel nickname= new javax.swing.JLabel();
    private javax.swing.JPanel stats= new javax.swing.JPanel();
    private javax.swing.JPanel titulo = new javax.swing.JPanel();
    private javax.swing.JLabel trainerID= new javax.swing.JLabel();
    private javax.swing.JLabel type1= new javax.swing.JLabel();
    private javax.swing.JLabel type2= new javax.swing.JLabel();
    private javax.swing.JLabel vel= new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}